apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: dev-elasticsearch
spec:
  http:
    service:
      spec:
        type: ClusterIP
  version: 8.9.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        
# curl https://github.com/duydo/elasticsearch-analysis-vietnamese/releases/download/v8.7.0/elasticsearch-analysis-vietnamese-8.7.0.zip -o elasticsearch-analysis-vietnamese-8.7.0.zip


                




