apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: dev-logstash
spec:
  version: 8.9.0
  count: 1
  elasticsearchRefs:
    - clusterName: dev-elasticsearch
      name: dev-elasticsearch
  pipelines:
    - pipeline.id: users-pipeline
      config.string: |
        input {
          jdbc {
            jdbc_connection_string => "jdbc:postgresql://db.ctxvsrfwmbfxsodwuvxv.supabase.co:5432/postgres"
            jdbc_user => "postgres"
            jdbc_password => "aura.shecom.asia.72nct"
            jdbc_driver_class => "org.postgresql.Driver"
            jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-jdbc.jar"
            jdbc_paging_enabled => true
            jdbc_page_size => "100000"
            tracking_column => "updated_at"
            use_column_value => true
            schedule => "*/1 * * * *"
            statement => "
              SELECT
                users.id as id,
                users.updated_at as updated_at,
                users.created_at as created_at,
                users.name as name,
                users.phone as phone,
                users.avatar as avatar,
                users.customer_resource as resource_name,
                agencies.name as agency,
                cs1.name as interact_result,
                cs2.name as details_status,
                advertises.name as ads,
                categories.name as categories,
                staffs.name as telesale,
                cr.label as resource_label
              FROM users
                LEFT JOIN customer_resources as cr ON users.customer_resource = cr.name
                LEFT JOIN agencies on users.agency_id = agencies.id
                LEFT JOIN customer_status as cs1 ON users.interact_result = cs1.id
                LEFT JOIN customer_status as cs2 ON users.details_status = cs2.id
                LEFT JOIN advertises ON users.ads_id = advertises.id
                LEFT JOIN categories ON users.category_id = categories.id
                LEFT JOIN staffs ON users.service_staff = staffs.id
              WHERE EXTRACT(EPOCH FROM users.updated_at) > :sql_last_value
              GROUP BY users.id, cr.label, agencies.name, cs1.name, cs2.name, advertises.name, categories.name, staffs.name
              "
          }
        }
        filter {
          mutate {
            copy => { "id" => "[@metadata][_id]"}
          }
        }
        output {
          elasticsearch {
            hosts => "elasticsearch-dev.auradental.vn:443"
            user => "elastic"
            ssl => true
            password => "dmRmN34F7gp659vZ720Wpwv9"
            index => "users"
            document_type => "user"
            document_id => "%{[@metadata][_id]}"
          }
        }
    - pipeline.id: booking-pipeline
      config.string: |
        input {
          jdbc {
            jdbc_connection_string => "jdbc:postgresql://db.ctxvsrfwmbfxsodwuvxv.supabase.co:5432/postgres"
            jdbc_user => "postgres"
            jdbc_password => "aura.shecom.asia.72nct"
            jdbc_driver_class => "org.postgresql.Driver"
            jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-jdbc.jar"
            jdbc_paging_enabled => true
            jdbc_page_size => "100000"
            tracking_column => "updated_at"
            use_column_value => true
            schedule => "*/30 * * * * *"
            statement => "
              SELECT
                orders.id AS id,
                bookings.status AS status,
                bookings.date::text AS booking_date,
                bookings.time::text AS booking_time,
                clinics.name AS clinic_name,
                clinics.id AS clinic_id,
                MIN(users.name) AS user_name,
                MIN(users.avatar) AS user_avatar,
                MIN(users.phone) AS user_phone,
                MIN(staffs.name) AS staff_name
              FROM bookings
                JOIN orders ON orders.id = bookings.order_id
                JOIN clinics ON clinics.id = bookings.clinic_id
                JOIN users ON users.id = orders.user_id
                LEFT JOIN staffs ON staffs.id = orders.staff_creator_id
              WHERE EXTRACT(EPOCH FROM users.updated_at) > :sql_last_value
              GROUP BY orders.id, bookings.date, bookings.time, clinics.name, bookings.status,clinics.id
              "
          }
        }
        filter {
          mutate {
            copy => { "id" => "[@metadata][_id]"}
          }
         
        }
        output {
          elasticsearch {
            hosts => "elasticsearch-dev.auradental.vn:443"
            user => "elastic"
            ssl => true
            password => "dmRmN34F7gp659vZ720Wpwv9"
            index => "bookings"
            document_type => "booking"
            document_id => "%{[@metadata][_id]}"
          }
        }
    - pipeline.id: order-pipeline
      config.string: |
        input {
          jdbc {
            jdbc_connection_string => "jdbc:postgresql://db.ctxvsrfwmbfxsodwuvxv.supabase.co:5432/postgres"
            jdbc_user => "postgres"
            jdbc_password => "aura.shecom.asia.72nct"
            jdbc_driver_class => "org.postgresql.Driver"
            jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-jdbc.jar"
            jdbc_paging_enabled => true
            jdbc_page_size => "100000"
            tracking_column => "updated_at"
            use_column_value => true
            schedule => "*/30 * * * * *"
            statement => "
              SELECT
                orders.id AS id,
                orders.created_at,
                users.name AS user_name,
                users.phone AS user_phone,
                users.avatar AS user_avatar,
                clinics.name AS clinic_name,
                staffs.name AS staff_name
              FROM orders
                LEFT JOIN users ON users.id = orders.user_id
                LEFT JOIN clinics ON clinics.id = orders.clinic_id
                LEFT JOIN staffs ON staffs.id = orders.staff_creator_id
              GROUP BY orders.id, orders.created_at, users.avatar, users.name, clinics.name, staffs.name,users.phone
              "
          }
        }
        filter {
          mutate {
            copy => { "id" => "[@metadata][_id]"}
          }
          json {
            source => "note"
            target => "parsed_note"
          }
        }
        output {
          elasticsearch {
            hosts => "elasticsearch-dev.auradental.vn:443"
            user => "elastic"
            ssl => true
            password => "dmRmN34F7gp659vZ720Wpwv9"
            index => "orders"
            document_type => "order"
            document_id => "%{[@metadata][_id]}"
          }
        }


# curl https://jdbc.postgresql.org/download/postgresql-42.6.0.jar -o logstash-core/lib/jars/postgresql-jdbc.jar

