apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: dev-logstash
spec:
  version: 8.8.2
  count: 1
  elasticsearchRefs:
    - clusterName: dev-elasticsearch
      name: dev-elasticsearch
  pipelines:
    - pipeline.id: users-pipeline
      config.string: |
        input {
          jdbc {
          jdbc_connection_string => "jdbc:postgresql://db.ghukjxfokoeacobbajae.supabase.co:5432/postgres"
          jdbc_user => "postgres"
          jdbc_password => "aura.shecom.asia"
          jdbc_driver_class => "org.postgresql.Driver"
          jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-jdbc.jar"
          jdbc_paging_enabled => true
          jdbc_page_size => "100000"
          tracking_column => "updated_at"
          use_column_value => true
          schedule => "*/1 * * * *"
          statement => "SELECT *, CAST(note AS text) as note FROM users WHERE EXTRACT(EPOCH FROM updated_at) > :sql_last_value"
          }
        }
        filter {
          mutate {
            copy => { "id" => "[@metadata][_id]"}
          }
          json {
            source => "note"
            target => "parsed_note"
          }
        }
        output {
          elasticsearch {
            hosts => "elasticsearch-dev.auradental.vn:443"
            user => "elastic"
            ssl => true
            password => "O0cYLwF4F516nI5s7W7t2cu9"
            index => "users"
            document_type => "user"
            document_id => "%{[@metadata][_id]}"
          }
        }
   

# curl https://jdbc.postgresql.org/download/postgresql-42.6.0.jar -o logstash-core/lib/jars/postgresql-jdbc.jar
