input {
  jdbc {
    jdbc_connection_string => "jdbc:postgresql://db.ghukjxfokoeacobbajae.supabase.co:6543/postgres"
    jdbc_user => "postgres"
    jdbc_password => "aura.shecom.asia"
    jdbc_driver_class => "org.postgresql.Driver"
    statement => "SELECT * FROM public.\"clinics\""
  }
}
output {
  elasticsearch {
    hosts => ["https://api-kibana-dev.auradental.vn"]
    user => "elastic"
    password => "O0cYLwF4F516nI5s7W7t2cu9"
    index => "clinics"
    document_id => "%{id}"
    doc_as_upsert => true
  }
}
