apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: product-elasticsearch
spec:
  http:
    service:
      spec:
        type: ClusterIP
  version: 8.9.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        http.cors.enabled: true
        http.cors.allow-origin: "*"
        http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
        http.cors.allow-credentials: true

        








