apiVersion: v1
kind: Service
metadata:
  name: product-aura-api-service
  labels:
    app.kubernetes.io/name: aura-api
spec:
  selector:
    app.kubernetes.io/name: aura-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer