const VnProvinces = [
  "Ba Tháng Hai",
  "Cần Thơ",
  "Đà Nẵng",
  "Hải Phòng",
  "Hà Nội",
  "Hồ Chí Minh",
  "Bà Rịa–Vũng Tàu",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Ninh",
  "Lâm Đồng",
  "Đồng Nai",
  "Bến Tre",
  "Đắk Lắk",
  "Cà Mau",
  "Quảng Ninh",
  "Đồng Tháp",
  "An Giang",
  "Lâm Đồng",
  "Điện Biên",
  "Quảng Trị",
  "Quảng Bình",
  "Hà Tĩnh",
  "Quảng Ninh",
  "Hải Dương",
  "Hòa Bình",
  "Quảng Nam",
  "Thừa Thiên–Huế",
  "Hưng Yên",
  "Kon Tum",
  "Lạng Sơn",
  "Lào Cai",
  "An Giang",
  "Quảng Ninh",
  "Tiền Giang",
  "Nam Định",
  "Ninh Bình",
  "Khánh Hòa",
  "Khánh Hòa",
  "Ninh Thuận",
  "Bình Thuận",
  "Hà Nam",
  "Gia Lai",
  "Quảng Ngãi",
  "Bình Định",
  "Kiên Giang",
  "Đồng Tháp",
  "Sóc Trăng",
  "Sơn La",
  "Quảng Nam",
  "Long An",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Trà Vinh",
  "Phú Yên",
  "Tuyên Quang",
  "Quảng Ninh",
  "Phú Thọ",
  "Nghệ An",
  "Vĩnh Phúc",
  "Vĩnh Long",
  "Bà Rịa–Vũng Tàu",
  "Yên Bái",
  "Cao Bằng",
];
module.exports = {
  VnProvinces,
};
